spring.application.name=system_backend
server.port=8080

# 环境配置 (默认使用开发环境)
spring.profiles.active=dev

# 日志基础配置
logging.level.root=INFO
logging.level.com.example.system_backend=DEBUG

# SpringDoc OpenAPI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
